# -*- coding: utf-8 -*-
"""Project 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xGH24ARbKHMX1tRp2zioVbkF-GZnj0Yy

**NAMA : DIKY ANDRIANTO**
<br>**NIM : G.231.21.0151**</br>
**TEKNIK INFORMATIKA B SORE**
<br>**Project 2 Pertemuan 15**</br>
"""

# Import library
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#  import dataset csv
data = pd.read_csv('dataset.csv')

# membuat jarak
X = np.arange(1,13)

# membuat figur
fig = plt.figure(figsize=(10, 3))

# menentukan koordinat  untuk untuk bar chart
ax = fig.add_axes([0,0,1,1])

# Mark label sumbu
ax.set_xlabel('Bulan')
ax.set_ylabel('Curah Hujan (mm)')

# membuat bar chart
ax.bar(X + 0.00, data['1981-1990'], color = 'b', width = 0.25)
ax.bar(X + 0.25, data['1991-2000'], color = 'r', width = 0.25)
ax.bar(X + 0.50, data['2001-2010'], color = 'g', width = 0.25)

ax.legend(['1981-1990', '1991-2000', '2001-2010'], ncol=3, loc='upper center', frameon=False)

# Menambahkan garis horizontal
for d in [100, 200, 300, 400, 500, 600, 700]:
  if d != 700:
    plt.axhline(y=d, color='gray', linestyle='-', linewidth=0.3)
  else:
    plt.axhline(y=d, color='gray', linestyle=' ', linewidth=0.3)

# Mengatur skala sumbu x 1 - 12
ax.set_xticks(X + 0.25)
ax.set_xticklabels(np.arange(1, 13))

plt.show()

#import library dan datetime
import datetime
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

# Membuat data
data1 = [23, 25.2, 25.5, 24.8, 22.5, 22.2, 23, 22, 25.9]
data2 = [23.5, 25.3, 25.1, 25.5, 24.9, 25, 24.5, 24, 26]
data3 = [24, 25, 23.8, 23.9, 24, 24.1, 24, 22.9, 23]
# membuat range berdasar waktu
dates = pd.date_range(start='2023-07-24', periods=9, freq='3H')

plt.figure(figsize=(10, 4))

# Membuat plot
plt.plot(dates, data1, marker='o', color='b', label='Asimilasi')
plt.plot(dates, data2, marker='o', color='r', label='Observasi')
plt.plot(dates, data3, marker='o', color='y', label='Non Asimilasi')

# Menambahkan label sumbu x y dan judul plot
plt.xlabel('Waktu')
plt.ylabel('Celcius')
plt.title('Suhu Permukaan')

# Menambahkan garis horizontal
for d in [20,21, 22, 23, 24, 25, 26, 27]:
  plt.axhline(y=d, color='gray', linestyle='-', linewidth=0.3)

# Mengatur skala sumbu x sebagai skala waktu
plt.gca().xaxis.set_major_formatter(mdates.DateFormatter('%H:%M UTC'))
plt.gca().xaxis.set_major_locator(mdates.AutoDateLocator())

plt.legend(loc="lower left")
plt.show()